# This is a basic workflow to help you get started with Actions

name: Echo

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Enter a message'
        required: true
        default: 'Hello, World!'

jobs:
  build:
    runs-on: self-hosted
#     defaults:
#       run:
#         shell: "/usr/bin/arch -arch arm64e /bin/bash {0}"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Print the message
        run: echo ${{ github.event.inputs.message }}
        
      - name: Architecture
        run: uname -m

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
